- name: Deploy WordPress usando container
  hosts: docker
  become: true

  tasks:
    - name: Start MySQL container
      docker_container:
        name: mysql
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password1982
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: password1982
    - name: Start WordPress container
      docker_container:
        name: wordpress
        image: wordpress:latest
        env:
          WORDPRESS_DB_HOST: mysql:3306
          WORDPRESS_DB_NAME: wordpress
          WORDPRESS_DB_USER: wordpress
          WORDPRESS_DB_PASSWORD: password1982 
        ports:
          - "80:80"
